import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StoreContextProvider } from '@/contexts/storeContext'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Task Mongo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <StoreContextProvider>
          {children}
        </StoreContextProvider>
      </body>
    </html>
  );
}
